// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using S401A2.Model.EntityFramework;

#nullable disable

namespace S401A2.Migrations
{
    [DbContext(typeof(CubeDBContext))]
    [Migration("20260312181326_OmitIfNull")]
    partial class OmitIfNull
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("public")
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("S401A2.Model.EntityFramework.Article", b =>
                {
                    b.Property<int>("ArticleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("art_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ArticleId"));

                    b.Property<int>("Annee")
                        .HasColumnType("integer")
                        .HasColumnName("art_annee");

                    b.Property<int>("CategorieId")
                        .HasColumnType("integer")
                        .HasColumnName("cat_id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("art_description");

                    b.Property<bool>("DispoEnLigne")
                        .HasColumnType("boolean")
                        .HasColumnName("art_dispo_en_ligne");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("art_nom");

                    b.Property<decimal>("Poids")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("art_poids");

                    b.Property<decimal>("Prix")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("art_prix");

                    b.Property<int>("QteStock")
                        .HasColumnType("integer")
                        .HasColumnName("art_qte_stock");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("art_reference");

                    b.HasKey("ArticleId");

                    b.HasIndex("CategorieId");

                    b.ToTable("t_e_article_art", "public");
                });

            modelBuilder.Entity("S401A2.Model.EntityFramework.Categorie", b =>
                {
                    b.Property<int>("CategorieId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("cat_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CategorieId"));

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("cat_nom");

                    b.HasKey("CategorieId");

                    b.ToTable("t_e_categorie_cat", "public");
                });

            modelBuilder.Entity("S401A2.Model.EntityFramework.Article", b =>
                {
                    b.HasOne("S401A2.Model.EntityFramework.Categorie", "CategorieArticle")
                        .WithMany("Articles")
                        .HasForeignKey("CategorieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CategorieArticle");
                });

            modelBuilder.Entity("S401A2.Model.EntityFramework.Categorie", b =>
                {
                    b.Navigation("Articles");
                });
#pragma warning restore 612, 618
        }
    }
}
