// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using S401A2.Model.EntityFramework;

#nullable disable

namespace S401A2.Migrations
{
    [DbContext(typeof(CubeDBContext))]
    partial class CubeDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("public")
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("APICube.Models.EntityFramework.Civilite", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("civ_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)")
                        .HasColumnName("div_nom");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Id" }, "civilite_pk")
                        .IsUnique();

                    b.ToTable("t_e_civilite_civ", "public");
                });

            modelBuilder.Entity("APICube.Models.EntityFramework.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("cli_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AdresseId")
                        .HasColumnType("integer")
                        .HasColumnName("adr_id");

                    b.Property<int>("CiviliteId")
                        .HasColumnType("integer")
                        .HasColumnName("civ_id");

                    b.Property<DateOnly?>("DateNaissance")
                        .IsRequired()
                        .HasColumnType("date")
                        .HasColumnName("client_datenaissance");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(75)
                        .HasColumnType("character varying(75)")
                        .HasColumnName("cli_email");

                    b.Property<string>("Mdp")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("cli_mdp");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("cli_nom");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("cli_prenom");

                    b.Property<int?>("Role")
                        .IsRequired()
                        .HasColumnType("integer")
                        .HasColumnName("cli_role");

                    b.HasKey("Id");

                    b.HasIndex("AdresseId");

                    b.HasIndex("CiviliteId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Id");

                    b.HasIndex("Nom");

                    b.HasIndex("Prenom");

                    b.ToTable("t_e_client_cli", "public");
                });

            modelBuilder.Entity("APICube.Models.EntityFramework.Commande", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("com_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AdresseIdFact")
                        .HasColumnType("integer")
                        .HasColumnName("adr_idfacturation");

                    b.Property<int>("AdresseIdLivr")
                        .HasColumnType("integer")
                        .HasColumnName("adr_idlivraison");

                    b.Property<int>("ClientId")
                        .HasColumnType("integer")
                        .HasColumnName("cli_id");

                    b.Property<string>("Livraison")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("com_livraison");

                    b.HasKey("Id");

                    b.HasIndex("AdresseIdFact");

                    b.HasIndex("AdresseIdLivr");

                    b.HasIndex("ClientId");

                    b.HasIndex("Id");

                    b.ToTable("t_e_commande_com", "public");
                });

            modelBuilder.Entity("APICube.Models.EntityFramework.Velo", b =>
                {
                    b.Property<int>("IdVelo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("idVelo");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdVelo"));

                    b.Property<int>("IdArticle")
                        .HasColumnType("integer")
                        .HasColumnName("idarticle");

                    b.Property<int>("IdModele")
                        .HasColumnType("integer")
                        .HasColumnName("idmodele");

                    b.Property<string>("LienVue360")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("lienvue360");

                    b.HasKey("IdVelo");

                    b.HasIndex("IdModele");

                    b.ToTable("t_e_velo_vel", "public");
                });

            modelBuilder.Entity("ArticleMotCle", b =>
                {
                    b.Property<int>("ArticlesArticleId")
                        .HasColumnType("integer");

                    b.Property<int>("MotsClesMotCleId")
                        .HasColumnType("integer");

                    b.HasKey("ArticlesArticleId", "MotsClesMotCleId");

                    b.HasIndex("MotsClesMotCleId");

                    b.ToTable("t_j_article_motcle_amc", "public");
                });

            modelBuilder.Entity("CadreVelo", b =>
                {
                    b.Property<int>("CadresIdMateriau")
                        .HasColumnType("integer");

                    b.Property<int>("VelosIdVelo")
                        .HasColumnType("integer");

                    b.HasKey("CadresIdMateriau", "VelosIdVelo");

                    b.HasIndex("VelosIdVelo");

                    b.ToTable("CadreVelo", "public");
                });

            modelBuilder.Entity("CouleurVelo", b =>
                {
                    b.Property<int>("CouleursIdCouleur")
                        .HasColumnType("integer");

                    b.Property<int>("VelosIdVelo")
                        .HasColumnType("integer");

                    b.HasKey("CouleursIdCouleur", "VelosIdVelo");

                    b.HasIndex("VelosIdVelo");

                    b.ToTable("CouleurVelo", "public");
                });

            modelBuilder.Entity("GeometrieVelo", b =>
                {
                    b.Property<int>("GeometriesIdGeometrie")
                        .HasColumnType("integer");

                    b.Property<int>("VelosIdVelo")
                        .HasColumnType("integer");

                    b.HasKey("GeometriesIdGeometrie", "VelosIdVelo");

                    b.HasIndex("VelosIdVelo");

                    b.ToTable("GeometrieVelo", "public");
                });

            modelBuilder.Entity("S401A2.Model.EntityFramework.Adresse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("adr_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CodePostale")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)")
                        .HasColumnName("adr_codepostale");

                    b.Property<string>("Pays")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("adr_pays");

                    b.Property<string>("Rue")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("adr_rue");

                    b.Property<string>("Ville")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("adr_ville");

                    b.HasKey("Id");

                    b.HasIndex("CodePostale");

                    b.HasIndex("Id");

                    b.HasIndex("Ville");

                    b.ToTable("t_e_adresse_adr", "public");
                });

            modelBuilder.Entity("S401A2.Model.EntityFramework.Article", b =>
                {
                    b.Property<int>("ArticleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("art_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ArticleId"));

                    b.Property<int>("Annee")
                        .HasColumnType("integer")
                        .HasColumnName("art_annee");

                    b.Property<int>("CategorieId")
                        .HasColumnType("integer")
                        .HasColumnName("cat_id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("art_description");

                    b.Property<bool>("DispoEnLigne")
                        .HasColumnType("boolean")
                        .HasColumnName("art_dispo_en_ligne");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("art_nom");

                    b.Property<decimal>("Poids")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("art_poids");

                    b.Property<decimal>("Prix")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("art_prix");

                    b.Property<int>("QteStock")
                        .HasColumnType("integer")
                        .HasColumnName("art_qte_stock");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("art_reference");

                    b.HasKey("ArticleId");

                    b.HasIndex("ArticleId");

                    b.HasIndex("CategorieId");

                    b.HasIndex("DispoEnLigne");

                    b.HasIndex("Prix");

                    b.HasIndex("Reference");

                    b.ToTable("t_e_article_art", "public");
                });

            modelBuilder.Entity("S401A2.Model.EntityFramework.Cadre", b =>
                {
                    b.Property<int>("IdMateriau")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("cad_id_materiau");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdMateriau"));

                    b.Property<string>("FormeCadre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("cad_forme");

                    b.Property<string>("NomMat")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("cad_nom_mat");

                    b.HasKey("IdMateriau");

                    b.ToTable("t_s_cadre_cad", "public");
                });

            modelBuilder.Entity("S401A2.Model.EntityFramework.Categorie", b =>
                {
                    b.Property<int>("CategorieId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("cat_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CategorieId"));

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("cat_nom");

                    b.HasKey("CategorieId");

                    b.ToTable("t_e_categorie_cat", "public");
                });

            modelBuilder.Entity("S401A2.Model.EntityFramework.Couleur", b =>
                {
                    b.Property<int>("IdCouleur")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("clr_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdCouleur"));

                    b.Property<string>("EffetPeinture")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("clr_effet_peinture");

                    b.Property<string>("NomCouleur")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("clr_nom");

                    b.HasKey("IdCouleur");

                    b.ToTable("t_s_couleur_clr", "public");
                });

            modelBuilder.Entity("S401A2.Model.EntityFramework.Geometrie", b =>
                {
                    b.Property<int>("IdGeometrie")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("geo_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdGeometrie"));

                    b.Property<string>("NomPiece")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("geo_nom_piece");

                    b.Property<decimal>("TaillePiece")
                        .HasColumnType("numeric")
                        .HasColumnName("geo_taille_piece");

                    b.HasKey("IdGeometrie");

                    b.ToTable("t_s_geometrie_geo", "public");
                });

            modelBuilder.Entity("S401A2.Model.EntityFramework.LignePanier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("lig_idpanier");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ArticleId")
                        .HasColumnType("integer")
                        .HasColumnName("art_id");

                    b.Property<int>("ClientId")
                        .HasColumnType("integer")
                        .HasColumnName("cli_id");

                    b.Property<int>("CommandeId")
                        .HasColumnType("integer")
                        .HasColumnName("com_id");

                    b.Property<int>("QtePanier")
                        .HasColumnType("integer")
                        .HasColumnName("lig_qtepanier");

                    b.HasKey("Id");

                    b.HasIndex("ArticleId");

                    b.HasIndex("ClientId");

                    b.HasIndex("Id");

                    b.HasIndex("QtePanier");

                    b.ToTable("t_e_lignepanier_lig", "public");
                });

            modelBuilder.Entity("S401A2.Model.EntityFramework.Modele", b =>
                {
                    b.Property<int>("IdModele")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("mod_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdModele"));

                    b.Property<string>("NomModele")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("mod_nom");

                    b.HasKey("IdModele");

                    b.ToTable("t_e_modele_mod", "public");
                });

            modelBuilder.Entity("S401A2.Model.EntityFramework.MotCle", b =>
                {
                    b.Property<int>("MotCleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("mcl_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MotCleId"));

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("mcl_nom");

                    b.HasKey("MotCleId");

                    b.ToTable("t_e_motcle_mcl", "public");
                });

            modelBuilder.Entity("S401A2.Model.EntityFramework.Taille", b =>
                {
                    b.Property<int>("IdTaille")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("tli_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdTaille"));

                    b.Property<string>("LibelleTaille")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tli_libelle");

                    b.HasKey("IdTaille");

                    b.ToTable("t_s_taille_tli", "public");
                });

            modelBuilder.Entity("TailleVelo", b =>
                {
                    b.Property<int>("TaillesIdTaille")
                        .HasColumnType("integer");

                    b.Property<int>("VelosIdVelo")
                        .HasColumnType("integer");

                    b.HasKey("TaillesIdTaille", "VelosIdVelo");

                    b.HasIndex("VelosIdVelo");

                    b.ToTable("TailleVelo", "public");
                });

            modelBuilder.Entity("APICube.Models.EntityFramework.Client", b =>
                {
                    b.HasOne("S401A2.Model.EntityFramework.Adresse", "AdresseClient")
                        .WithMany("AdresseClient")
                        .HasForeignKey("AdresseId");

                    b.HasOne("APICube.Models.EntityFramework.Civilite", "CiviliteClient")
                        .WithMany("CiviliteClient")
                        .HasForeignKey("CiviliteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AdresseClient");

                    b.Navigation("CiviliteClient");
                });

            modelBuilder.Entity("APICube.Models.EntityFramework.Commande", b =>
                {
                    b.HasOne("S401A2.Model.EntityFramework.Adresse", "AdresseCommandeFact")
                        .WithMany("AdresseCommandeFact")
                        .HasForeignKey("AdresseIdFact");

                    b.HasOne("S401A2.Model.EntityFramework.Adresse", "AdresseCommandeLivr")
                        .WithMany("AdresseCommandeLivr")
                        .HasForeignKey("AdresseIdLivr")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("APICube.Models.EntityFramework.Client", "ClientCommande")
                        .WithMany("ClientCommande")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AdresseCommandeFact");

                    b.Navigation("AdresseCommandeLivr");

                    b.Navigation("ClientCommande");
                });

            modelBuilder.Entity("APICube.Models.EntityFramework.Velo", b =>
                {
                    b.HasOne("S401A2.Model.EntityFramework.Modele", "ModeleVelo")
                        .WithMany("Velos")
                        .HasForeignKey("IdModele")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ModeleVelo");
                });

            modelBuilder.Entity("ArticleMotCle", b =>
                {
                    b.HasOne("S401A2.Model.EntityFramework.Article", null)
                        .WithMany()
                        .HasForeignKey("ArticlesArticleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("S401A2.Model.EntityFramework.MotCle", null)
                        .WithMany()
                        .HasForeignKey("MotsClesMotCleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CadreVelo", b =>
                {
                    b.HasOne("S401A2.Model.EntityFramework.Cadre", null)
                        .WithMany()
                        .HasForeignKey("CadresIdMateriau")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("APICube.Models.EntityFramework.Velo", null)
                        .WithMany()
                        .HasForeignKey("VelosIdVelo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CouleurVelo", b =>
                {
                    b.HasOne("S401A2.Model.EntityFramework.Couleur", null)
                        .WithMany()
                        .HasForeignKey("CouleursIdCouleur")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("APICube.Models.EntityFramework.Velo", null)
                        .WithMany()
                        .HasForeignKey("VelosIdVelo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GeometrieVelo", b =>
                {
                    b.HasOne("S401A2.Model.EntityFramework.Geometrie", null)
                        .WithMany()
                        .HasForeignKey("GeometriesIdGeometrie")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("APICube.Models.EntityFramework.Velo", null)
                        .WithMany()
                        .HasForeignKey("VelosIdVelo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("S401A2.Model.EntityFramework.Article", b =>
                {
                    b.HasOne("S401A2.Model.EntityFramework.Categorie", "CategorieArticle")
                        .WithMany("Articles")
                        .HasForeignKey("CategorieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CategorieArticle");
                });

            modelBuilder.Entity("S401A2.Model.EntityFramework.LignePanier", b =>
                {
                    b.HasOne("S401A2.Model.EntityFramework.Article", "ArticleLignePanier")
                        .WithMany("ArticleLignePanier")
                        .HasForeignKey("ArticleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("APICube.Models.EntityFramework.Client", "ClientLignePanier")
                        .WithMany("ClientLignePanier")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ArticleLignePanier");

                    b.Navigation("ClientLignePanier");
                });

            modelBuilder.Entity("TailleVelo", b =>
                {
                    b.HasOne("S401A2.Model.EntityFramework.Taille", null)
                        .WithMany()
                        .HasForeignKey("TaillesIdTaille")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("APICube.Models.EntityFramework.Velo", null)
                        .WithMany()
                        .HasForeignKey("VelosIdVelo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("APICube.Models.EntityFramework.Civilite", b =>
                {
                    b.Navigation("CiviliteClient");
                });

            modelBuilder.Entity("APICube.Models.EntityFramework.Client", b =>
                {
                    b.Navigation("ClientCommande");

                    b.Navigation("ClientLignePanier");
                });

            modelBuilder.Entity("S401A2.Model.EntityFramework.Adresse", b =>
                {
                    b.Navigation("AdresseClient");

                    b.Navigation("AdresseCommandeFact");

                    b.Navigation("AdresseCommandeLivr");
                });

            modelBuilder.Entity("S401A2.Model.EntityFramework.Article", b =>
                {
                    b.Navigation("ArticleLignePanier");
                });

            modelBuilder.Entity("S401A2.Model.EntityFramework.Categorie", b =>
                {
                    b.Navigation("Articles");
                });

            modelBuilder.Entity("S401A2.Model.EntityFramework.Modele", b =>
                {
                    b.Navigation("Velos");
                });
#pragma warning restore 612, 618
        }
    }
}
