name: Deploy and Migrate C# Database

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Execute Migration via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.ALWAYSDATA_SSH_HOST }}
          username: ${{ secrets.ALWAYSDATA_SSH_USER }}
          password: ${{ secrets.ALWAYSDATA_SSH_PASSWORD }}
          script: |
            export DOTNET_ROOT=/usr/alwaysdata/dotnet/8.0.23
            export PATH="$DOTNET_ROOT:$HOME/.dotnet/tools:$PATH"
            cd $HOME/www/
            git fetch origin main
            git reset --hard origin/main
            cd Backend/
            dotnet ef database update
